### ISSUE TITLE
[Feature] 핸드폰에서 찍은 사진 업로드 시 CORS 에러 발생

### ISSUE THREAD

**Issue by Yangseungchan** [boostcampwm-2022/web13-moyeomoyeo#194]
## 요구 사항

![이미지업로드에러](https://user-images.githubusercontent.com/38908080/205559550-7dd3d75b-61bd-43a4-81fa-728bb9104d1d.gif)

![image](https://user-images.githubusercontent.com/38908080/205559784-7d1d5ece-13dd-44fe-bdc8-2edff3f90107.png)

- 핸드폰에서 찍은 사진 업로드 시 CORS에러(413) 발생
  - 어느 디바이스에서 업로드했는지가 아니라 어느 디바이스에서 찍은 사진을 업로드했는지에 따라 에러 발생 양상이 달라짐
  - 핸드폰에서 찍은 사진을 올리면 413 에러 발생
  - PC에서 핸드폰으로부터 전달받은 사진을 올려도 동일한 에러 발생
  - PC에서 용량이 큰 이미지(2메가 이상)을  올리는건 에러가 발생하지 않음 

## 체크 리스트

- [x] 이미지 업로드 에러 고치기

**Comment by username1103** [comment]
확인해본 결과, 휴대폰에서 찍은 사진이라서가 아니라 용량때문인 것으로 확인돼요. 

서버 앞단에 있는 nginx에서 기본적으로 클라이언트 요청의 최대 body size가 1mb로 설정되어있어요. 그렇다보니 nginx에서 413 Payload Too Large를 응답하게돼요. 근데 cors설정을 서버에서 하다보니 nginx에서 바로 반환될 경우 cors설정없이 반환되기 때문에 cors에러도 함께 발생하는 것 같습니다.
