### ISSUE TITLE
[Feature] 백엔드 개발 셋팅

### ISSUE THREAD

**Issue by username1103** [boostcampwm-2022/web13-moyeomoyeo#7]
## 요구 사항

- 백엔드 개발 환경 셋팅

## 체크 리스트

- [x] yarn berry
- [x] NestJS
  - [x] eslint
  - [x] prettier

## 비고

- 참고 사항을 적어주세요. 해당 작업을 하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

**Comment by pythonstrup** [comment]
백엔드 기본 세팅 완료
